@ stdcall InitSecurityInterfaceA()
@ stdcall InitSecurityInterfaceW()
@ stdcall CP_AcquireCredentialsHandleA(str str long ptr ptr ptr ptr ptr ptr)
@ stdcall CP_AcquireCredentialsHandleW(wstr wstr long ptr ptr ptr ptr ptr ptr)
@ stdcall CP_FreeCredentialsHandle(ptr)
@ stdcall CP_InitializeSecurityContextA(ptr ptr str long long long ptr long ptr ptr ptr ptr)
@ stdcall CP_InitializeSecurityContextW(ptr ptr wstr long long long ptr long ptr ptr ptr ptr)
@ stdcall CP_DeleteSecurityContext(ptr)
@ stdcall CP_QueryContextAttributes(ptr long ptr)
@ stdcall CP_EncryptMessage(ptr long ptr long)
@ stdcall CP_DecryptMessage(ptr ptr long ptr)
@ stdcall CP_ApplyControlToken(ptr ptr)
@ stdcall CP_FreeContextBuffer(ptr)
